Rails.application.routes.draw do
  # get  '/index', to: 'store#index'
  # get  '/contact', to: 'store#contact'
  # get  '/shop', to: 'store#shop'
  # get  '/about', to: 'store#about'
  # get  '/shop_single', to: 'store#shop_single'

  # get  '/testimonial', to: 'giftos#testimonial'
  # get  '/why', to: 'giftos#why'

  # get 'sequences', to: 'sequences#index'
  # get 'sequences/check', to: 'sequences#check'
  # root 'sequences#index'
  resources :stroyka_store_tools

  get '/about', to: 'stroyka_store_tools#about'
  get '/terms-and-conditions', to: 'stroyka_store_tools#terms-and-conditions'
  
  get '/account', to: 'stroyka_store_tools#account'
  get '/blog', to: 'stroyka_store_tools#blog'
  get '/cart', to: 'stroyka_store_tools#cart'
  get '/checkout', to: 'stroyka_store_tools#checkout'
  get '/compare', to: 'stroyka_store_tools#compare'
  get '/components', to: 'stroyka_store_tools#components'
  get '/contact_us', to: 'stroyka_store_tools#contact_us'
  get '/contact_us_alt', to: 'stroyka_store_tools#contact_us_alt'
  get '/faq', to: 'stroyka_store_tools#faq'
  get '/index', to: 'stroyka_store_tools#index'
  get '/post', to: 'stroyka_store_tools#post'
  get '/about-us', to: 'stroyka_store_tools#about-us'
  get '/post-without-sidebar', to: 'stroyka_store_tools#post-without-sidebar'
  get '/product', to: 'stroyka_store_tools#product'
  get '/shop', to: 'stroyka_store_tools#shop'
  get '/terms', to: 'stroyka_store_tools#terms'
  get '/trackorder', to: 'stroyka_store_tools#trackorder'
  get '/typography', to: 'stroyka_store_tools#typography'
  get '/wishlist', to: 'stroyka_store_tools#wishlist'
  get '/shop-grid-3-columns-sidebar', to: 'stroyka_store_tools#shop-grid-3-columns-sidebar'
  get '/index_2', to: 'stroyka_store_tools#index_2'
  get '/shop-grid-4-columns-full', to: 'stroyka_store_tools#shop-grid-4-columns-full'
  get '/shop-list', to: 'stroyka_store_tools#shop-list'
  get '/shop-right-sidebar', to: 'stroyka_store_tools#shop-right-sidebar'
  get '/product-alt', to: 'stroyka_store_tools#product-alt'
  get '/product-sidebar', to: 'stroyka_store_tools#product-sidebar'
  get '/track-order', to: 'stroyka_store_tools#track-order'
  get '/blog-classic', to: 'stroyka_store_tools#blog-classic'
  get '/blog-grid', to: 'stroyka_store_tools#blog-grid'
  get '/blog-list', to: 'stroyka_store_tools#blog-list'
  get '/blog-left-sidebar', to: 'stroyka_store_tools#blog-left-sidebar'

end
